config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root "index_pages#home"
  
  get "about" => "index_pages#about"
  get "signup" => "users#new"
  get 'login' => 'sessions#new'
  
  post 'login' => 'sessions#create'
  post 'vote' => 'posts#voting'
  
  delete 'logout' => 'sessions#destroy'
  resources :users
  resources :posts
end

app/models/option.rb
class Option < ActiveRecord::Base
  belongs_to :post
  before_create { self.name = '' }
  before_create { self.count = 0 }
  
  validates :value,  presence: true, length: { maximum: 255 }
  default_scope -> { order(count: :desc) }
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :options, dependent: :destroy
  accepts_nested_attributes_for :options, reject_if: :all_blank, allow_destroy: true, update_only: true
  
  validates :title,  presence: true, length: { maximum: 255 }
  validates :vote_limit, :numericality => { :greater_than => 0 }
  default_scope -> { order(created_at: :desc) }
  
  validate :start_date_before_end_date
  validate :must_have_at_least_2_options
  validate :vote_limit_must_less_than_number_of_options
  
  def start_date_before_end_date
    if !start_date.nil? && !close_date.nil?
      if start_date > close_date
        errors.add(:start_date, "Must Occur Before End Date")
      end
    end
  end
  
  def must_have_at_least_2_options
    if self.options.length < 2
      errors.add(:options, "Not enough option")
    end
  end
  
  def vote_limit_must_less_than_number_of_options
    if self.options.length <= self.vote_limit
      errors.add(:vote_limit, "Vote limit can not be equal to or greater than number of options")
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token
  has_many :posts, dependent: :destroy
  
  # before filter
  before_save { self.email = email.downcase }
  
  # validation
  validates :name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 8 }, allow_nil: true
  
  has_secure_password
  
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include UsersHelper
  include SessionsHelper
  include PostsHelper
  
    
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in"
      redirect_to login_url
    end
  end
end

app/controllers/index_pages_controller.rb
class IndexPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user, only: [:create, :new]
  
  def index
    @posts = Post.paginate(page: params[:page])
  end
  
  def show
    @post = Post.find(params[:id])
    @options = @post.options
    @is_voted = false
  end
  
  def new
    @post = Post.new
    @post.options.build
  end
  
  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post
      flash[:success] = "Post created successfully"
    else
      render 'new'
    end
  end
  
  def voting
    po = Post.find(params[:options][:post_id])
    if !params[:options_id]
      if params[:option_id].length <= po.vote_limit
        params[:option_id].each do |o|
          opt = Option.find(o.to_i)
          opt.update_attributes(count: (opt.count + 1).to_s)
          opt.update_attributes(name: opt.name + current_user.id.to_s + ",")
        end
        flash[:success] = "Voted successfully"
        redirect_to po
      else
        flash[:danger] = "Vote limit exceeded" 
        redirect_to po
      end
    else
      flash[:danger] = "No vote committed" 
      redirect_to po
    end
  end
  
  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      flash[:success] = "Update succeeded"
      redirect_to @post
    else
      render 'show'
    end
  end
  
  private
    def post_params
      params.require(:post).permit(:title, :description, :enable_adding, :allow_anonymous_voting,
                                   :close_date, :start_date, :background_img, :user_id, :vote_limit,
                                   options_attributes: [:id, :value, :description, :img, :count, :name, :_destroy])
    end
    
    # def is_voted (po)
    #   options = po.options
    #   options.each do |option|
    #     if option.name.split(',').include? current_user.id.to_s
    #       return true
    #     end
    #   end
    #   return false
    # end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in(user)
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_back_or posts_url
    else
      flash[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end
  
  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update]
  before_action :correct_user, only: [:edit, :update]
  
  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to posts_url
      flash[:success] = "Welcome to Poll Creating App"
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
    
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Voting Poll Web App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
  
end

app/helpers/index_pages_helper.rb
module IndexPagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def user_name(opt)
      ids = opt.name.to_s.split(',')
      names = Array.new
      ids.each do |id|
        user = User.find(id)
        names.push(user.name)
      end
      return names
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end
  
  def logged_in?
    !current_user.nil?
  end
  
  def log_out
    forget(@current_user)
    session.delete(:user_id)
    @current_user = nil
  end
  
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end
  
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
    
  def current_user?(user)
    user == current_user
  end
  
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end
  
  def store_location
    session[:forwarding_url] = request.url if request.get?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/index_pages/about.html.erb
<h1>POCRE APP</h1>
<p>Create polls</p>

app/views/index_pages/home.html.erb
<div class="center jumbotron">
  
  <h1 class="name">| pocre |<br>poll creating web app.</h1>
  <br>
  <hr>
  <div id=below>
    <br>
    <h2>
      It helps you create and manage your own poll
    </h2>
    <br>
    <% if !logged_in? %>
     <%= link_to "Sign up", signup_path, class: "btn btn-lg btn-default" %>
    <% else %>
      <%= link_to "Create Poll", new_post_path, class: "btn btn-lg btn-default" %>
    <% end %>
    <br>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <hr>
  <small>
    The Poll Creating Web App by Dung Bui and Ha Nguyen
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="container">
    <nav>
      <br>
      <div id="menu">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", root_path %></li>
          <% if current_user != nil %>
            <li><%= link_to "Create", new_post_path %></li>
          <% end %>
          <li><%= link_to "Polls", posts_url %></li>
          <li><%= link_to "About", about_path %></li>
          <% if logged_in? %>
            <li><%= link_to "Settings", edit_user_path(current_user) %></li>
            <li class="divider"></li>
            <li>
              <%= link_to "Log out", logout_path, method: "delete" %>
            </li>

          <% else %>
            <li><%= link_to "Log in", login_path %></li>
          <% end %>
        </ul>
      </div>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag "https://www.google.com/jsapi", "chartkick" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="clear"></div>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
  <script type="text/javascript">
      $(function () {
          $('#datetimepicker1').datetimepicker(
            {format: 'YYYY-MM-DD HH:mm'}
          )
      });
  </script>
</html>

app/views/posts/_option_fields.html.erb
<div class="nested-fields">
    <div class="field">
      <%= f.label :value, "Value" %>
      <%= f.text_field :value %>
    </div>
    <div class="field">
      <%= f.label :description, "Description" %>
      <%= f.text_field :description %>
    </div>
    <div class="field">
      <%= f.label :img, "Image link" %>
      <%= f.text_field :img %>
    </div>
    <%= link_to_remove_association "remove option", f, class: "btn btn-danger pull-right" %>
</div>

app/views/posts/index.html.erb
<% provide(:title, 'All Polls') %>
<h1>All Polls</h1>
<hr>
<br>

<%= will_paginate %>
<ul class="polls">
  <% @posts.each do |po| %>
    <li>
      <%= link_to po.title, po %>
    </li>
  <% end %>
</ul>
<%= will_paginate %>

app/views/posts/new.html.erb
<% provide(:title, "Creating Poll") %>
<h1>creating poll.</h1>
<hr>
<br>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@post) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      
      <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.hidden_field :start_date, value: DateTime.now %>
      <div class="field">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>
      
      <div class="field">
        <%= f.label :vote_limit %>
        <%= f.number_field :vote_limit, class: 'form-control' %>
      </div>
      
      <div class="field">
        <%= f.label :description %>
        <%= f.text_field :description, class: 'form-control' %>
      </div>
  
      <label>Poll Date Closed</label>
      <div class='input-group date controls' id='datetimepicker1' >
        <%= f.text_field :close_date, class: "form-control",id: "event_end_date"%>

        <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span>
        </span>
      </div>
      
      <br>
      <div class="field">
        <%= f.label :background_img, "Description Image" %>
        <%= f.text_field :background_img, class: 'form-control' %>
      </div>
      
      <h3>Options</h3>
      <div id="options">
        <%= f.fields_for :options do |option| %>
          <%= render 'option_fields', f: option %>
        <% end %>
        <div class="links">
          <%= link_to_add_association 'add option', f, :options, class: "btn btn-default" %>
        </div>
      </div>

      <br> 
      
      <%= f.submit "Create Poll", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

app/views/posts/show.html.erb
<% provide(:title, "Poll") %>
<h1><%= @post.title %></h1>
<hr>
<h2><%= @post.description %></h2><br>
<% if !@post.background_img.nil? %>
<div class="img img-div"><%= image_tag(@post.background_img, :alt => "background", :height => 400) %></div>
<% end %>
<h3>Share this link to people to vote:</h3>
<textarea rows='1' id='fe_text' wrap="hard" disabled><%= request.original_url %></textarea>
<button class='my_clip_button btn btn-lg btn-default pull-right' data-clipboard-target='fe_text' data-clipboard-text='Default clipboard text from attribute' id='d_clip_button' title='Click me to copy to clipboard.'>
  <b>Copy To Clipboard...</b>
</button>
<br>
<br>
<h3>Close date: <%= @post.close_date.to_formatted_s(:long) %></h3>
<br>
<div class="vertical-center clock"></div>
<br>
<br>
<% if current_user != nil %>
  <% if current_user.id != @post.user_id %>
    <% if @post.close_date > DateTime.now %>
      <% if !@is_voted %>
        <%= form_for :options, :url => vote_path do |f| %>
          <%= f.hidden_field :post_id, value: @post.id %>
          <% @options.each do |opt| %>
          <hr>
          <hr style="width: 50%">
          <div class="">
            <div style="text-align: center">
            <%= check_box_tag "option_id[]", opt.id %>
            <h2 style=""><%= opt.value %><br></h2>
            <h3><%= opt.description %></h3>
            </div>
            <% if !opt.img.nil? %>
              <div class="vertical-center img"><%= image_tag(opt.img, :alt => "background", :height => 150) %> </div><br>
            <% end %>
          </div>
          
          <% end %>
          <%= f.submit "Vote", class: "btn btn-primary", id:"margin" %>
        <% end %>
      <% else %>
        <p>You have already voted</p>
        <% @options.each do |opt| %>
          <%= opt.value %> <br>
          Description: <%= opt.description %> <br>
          <% if !opt.img.nil? %>
            <div class="vertical-center img"><%= image_tag(opt.img, :alt => "background", :height => 150) %> </div><br>
          <% end %>
          <%= pluralize(opt.count, "person") %> voted for this option. <br> <br>
        <% end %>
      <% end %>
    <%else %>
      <p>This poll has closed</p>
    <% end %>
  <% else %>
    <div class="row">
      <div class="col-xs-6">
        <h3>Total Votes</h3>
        <% votes = Hash.new %>
        <% @post.options.each do |opt| %>
          <% votes[opt.value.to_sym] = opt.count %>
        <% end %>
        <div>
          <%= pie_chart(votes) %>
        </div>
      </div>
    </div>
    <% @options.each do |opt| %>
      <div style="margin-top: 2em;" class="col-md-4">
      <%= opt.value %> <br>
      Description: <%= opt.description %> <br>
      <% if !opt.img.nil? %>
        <div class="vertical-center img"><%= image_tag(opt.img, :alt => "background", :height => 150) %> </div><br>
      <% end %>
      <%= pluralize(opt.count, "person") %> voted for this option. <br>
      <% if opt.count > 0 %>
      <% count = 0 %>
      Including: 
        <% user_name(opt).each do |n|%>
          <% count += 1 %>
          <%= n %>
          <% if count == opt.count %>
            .<br>
          <% else %>
            , 
          <% end %>
        <% end %>
      <% end %>
      <br> <br>
      </div>
    <% end %>
    <br>
    <h1 style="clear:both;">Edit the poll</h1>
    
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <%= form_for(@post) do |f| %>
          <%= render 'shared/error_messages', object: f.object %>
          
          <%= f.hidden_field :user_id, value: current_user.id %>
          <%= f.hidden_field :start_date, value: DateTime.now %>
          <div class="field">
            <%= f.label :title %>
            <%= f.text_field :title, class: 'form-control' %>
          </div>
          
          <div class="field">
            <%= f.label :vote_limit %>
            <%= f.number_field :vote_limit, class: 'form-control' %>
          </div>
          
          <div class="field">
            <%= f.label :description %>
            <%= f.text_field :description, class: 'form-control' %>
          </div>
      
          <label>Poll Date Closed</label>
          <div class='input-group date controls' id='datetimepicker1' >
            <%= f.text_field :close_date, class: "form-control",id: "event_end_date"%>
    
            <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span>
            </span>
          </div>
          
          <br>
          <div class="field">
            <%= f.label :background_img, "Description Image" %>
            <%= f.text_field :background_img, class: 'form-control' %>
          </div>
          
          <h3>Options</h3>
          <div id="options">
            <%= f.fields_for :options do |option| %>
              <%= render 'option_fields', f: option %>
            <% end %>
            <div class="links">
              <%= link_to_add_association 'add option', f, :options, class: "btn btn-default" %>
            </div>
          </div>
          <br>
          <br>
          <%= f.submit "Update Poll", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  <% end %>
<% else %>
  <% if @post.close_date > DateTime.now %>
    <%= form_for :options, :url => vote_path do |f| %>
      <%= f.hidden_field :post_id, value: @post.id %>
      <% @options.each do |opt| %>
      <hr>
      <hr style="width: 50%">
      <div class="">
        <div style="text-align: center">
        <%= check_box_tag "option_id[]", opt.id %>
        <h2 style=""><%= opt.value %><br></h2>
        <h3><%= opt.description %></h3>
        </div>
        <% if !opt.img.nil? %>
          <div class="vertical-center img"><%= image_tag(opt.img, :alt => "background", :height => 150) %> </div><br>
        <% end %>
      </div>
      
      <% end %>
      <%= f.submit "Vote", class: "btn btn-primary", id:"margin" %>
    <% end %>
  <% else %>
    <p>This poll has closed</p>
  <% end %>
<% end %>
  
<script type="text/javascript">
			var clock;
			$(document).ready(function() {
				// Instantiate a counter
				clock = new FlipClock($('.clock'), <%= @post.close_date-DateTime.now %>, {
					clockFace: 'DailyCounter',
					autoStart: true,
					countdown: true
				});
				
			});
		</script>
		
<script>
  $(document).ready(function() {
    var clip = new ZeroClipboard($("#d_clip_button"))
  });

  $("#clear-test").on("click", function(){
    $("#fe_text").val("Copy me!");
    $("#testarea").val("");
  });
  
//   $("#slide").css({width:$(window).width(),height:$(window).height()});
// 	function imgsize() {
// 	    var W = $(window).width(),
// 	        H = $(window).height();
	
// 	    $('#slide').height(H).width(W);
// 	}
// 	$(window).bind('resize', function() { imgsize(); });
</script>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>
<hr>
<br>


<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<hr>
<br>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>